# Generated by Django 3.2.10 on 2022-04-21 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20220421_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rate_content',
            new_name='rate_disease',
        ),
    ]
