# Generated by Django 3.2.10 on 2022-04-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0010_auto_20220421_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rate_content',
        ),
    ]
